/* DO NOT EDIT THIS FILE - it is machine generated */
#include <com_kbeta_jni_learnjni_StringJniTest.h>

/*
 * Class:     com_kbeta_jni_learnjni_StringJniTest
 * Method:    getString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_kbeta_jni_learnjni_StringJniTest_getString
  (JNIEnv *env , jclass jclzz){
    return (*env)->NewStringUTF(env,"hello jni");
  }
