/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_kbeta_jni_learnjni_ArrayJniTest */

#ifndef _Included_com_kbeta_jni_learnjni_ArrayJniTest
#define _Included_com_kbeta_jni_learnjni_ArrayJniTest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_kbeta_jni_learnjni_ArrayJniTest
 * Method:    getSumOfArray
 * Signature: ([I)I
 */
JNIEXPORT jint JNICALL Java_com_kbeta_jni_learnjni_ArrayJniTest_getSumOfArray
  (JNIEnv *, jclass, jintArray, jint);

#ifdef __cplusplus
}
#endif
#endif
