/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_kbeta_jni_learnjni_JniTest */

#ifndef _Included_com_kbeta_jni_learnjni_JniTest
#define _Included_com_kbeta_jni_learnjni_JniTest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_kbeta_jni_learnjni_JniTest
 * Method:    getInt
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_kbeta_jni_learnjni_JniTest_getInt
  (JNIEnv *, jclass);

/*
 * Class:     com_kbeta_jni_learnjni_JniTest
 * Method:    getFloat
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_com_kbeta_jni_learnjni_JniTest_getFloat
  (JNIEnv *, jclass);

/*
 * Class:     com_kbeta_jni_learnjni_JniTest
 * Method:    getChar
 * Signature: ()C
 */
JNIEXPORT jchar JNICALL Java_com_kbeta_jni_learnjni_JniTest_getChar
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
