/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_kbeta_jni_learnjni_StringJniTest */

#ifndef _Included_com_kbeta_jni_learnjni_StringJniTest
#define _Included_com_kbeta_jni_learnjni_StringJniTest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_kbeta_jni_learnjni_StringJniTest
 * Method:    getString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_kbeta_jni_learnjni_StringJniTest_getString
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
