
/* DO NOT EDIT THIS FILE - it is machine generated */
#include <com_kbeta_jni_learnjni_StringJniTest.h>
#include <string.h>
/*
 * Class:     com_kbeta_jni_learnjni_StringJniTest
 * Method:    getString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_kbeta_jni_learnjni_StringJniTest_getString
  (JNIEnv *env , jclass jclzz){
    return (*env)->NewStringUTF(env,"hello jni");
  }

JNIEXPORT jstring JNICALL Java_com_kbeta_jni_learnjni_StringJniTest_accessField
   (JNIEnv *env, jobject jobj){
    jclass jclzz = (*env)->GetObjectClass(env,jobj);
    // 第三个参数为属性名称，第四个参数为签名 别拉下 签名后面那个分号
    jfieldID fid = (*env)->GetFieldID(env,jclzz,"key","Ljava/lang/String;");
    jstring jstr = (*env)->GetObjectField(env,jobj,fid);
    const char *c_str = (*env)->GetStringUTFChars(env,jstr,JNI_FALSE);
    char text[20] = "super ";
    strcat(text,c_str);
    jstring new_str  = (*env)->NewStringUTF(env,text);
    //顺便修改一下java对象里的值 如果下方这一行注释掉，java里对应的属性不会更改
    //(*env)->SetObjectField(env,jobj,fid,new_str);
    return new_str;

   }
