/* DO NOT EDIT THIS FILE - it is machine generated */
#include <com_kbeta_jni_learnjni_ArrayJniTest.h>

/*
 * Class:     com_kbeta_jni_learnjni_ArrayJniTest
 * Method:    getSumOfArray
 * Signature: ([I)I
 */
JNIEXPORT jint JNICALL Java_com_kbeta_jni_learnjni_ArrayJniTest_getSumOfArray
  (JNIEnv *env, jclass jclzz, jintArray arr,jint len){

    jint buf[len];
    jint i,sum =0;
    (*env)->GetIntArrayRegion(env, arr, 0, len, buf);

    for(i=0;i<len;i++){
        sum = sum + buf[i];
    }
    return sum;


  }

